---
name: Publish release
permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]
  workflow_dispatch: null

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm clean-install
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
