---
name: Update gh-pages
permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  update-gh-pages:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Merge main into gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge origin/main
          git push
